[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/send-mail"
  to = "/.netlify/functions/contact"
  status = 200

[[redirects]]
  from = "/api/send-mail"
  to = "/.netlify/functions/contact"
  status = 200
